### ISSUE TITLE
MacOS can not get gomoji dependency

### ISSUE THREAD

**Issue by xvilo** [oct2pus/emoji-dl#4]
Hi,

I'm trying to build it on macOS, but it get the following:

```
➜  go build
main.go:6:2: cannot find package "gomoji/emoji" in any of:
	/usr/local/Cellar/go/1.12.3/libexec/src/gomoji/emoji (from $GOROOT)
	/Users/xvilo/go/src/gomoji/emoji (from $GOPATH)
➜  emoji-dl-master: go get
package gomoji/emoji: unrecognized import path "gomoji/emoji" (import path does not begin with hostname)
➜  emoji-dl-master: go get gomoji/emoji
package gomoji/emoji: unrecognized import path "gomoji/emoji" (import path does not begin with hostname)
➜  emoji-dl-master: go get ./...
package gomoji/emoji: unrecognized import path "gomoji/emoji" (import path does not begin with hostname)
```

**Comment by oct2pus** [comment]
i apologize for being 2 weeks late, I'm going to up my notifications to "Watching" since I just assume I would get notified of new issues being posted.

the latest commits should've fixed this. The problem had nothing to do with MacOS, I simply renamed the project on github but I didn't modify the code to account for this. So I could build the project because I had residual folders from when it was called gomoji.
