### ISSUE TITLE
Unable to pull from a certain instance

### ISSUE THREAD

**Issue by clarjon1** [oct2pus/emoji-dl#7]
Hallo,

I'm unable to pull emojis from a particular instance, whomst.dog

```~$ emoji-dl --verbose whomst.dog
error: json: cannot unmarshal object into Go value of type []emoji.api```

**Comment by oct2pus** [comment]
I checked with curl, I got this:

```fish
oct2pus@desktop ~/C/emoji-dl> curl https://whomst.dog/api/v1/custom_emojis
{"error":"This API requires an authenticated user"}⏎
```
I notice [emojos.in](https://emojos.in) similarly crashes when checking out that community.

[Whomst.dog](https://whomst.dog) appears to crash when I view a user's profile as well; their nginx may be misconfigured or this might be intentional. Some input from their admin would be appreciated. 

However, I'm going to close this issue with WONT FIX since this appears to not be a problem on emoji-dl's end.
